In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df1=pd.read_csv('hospital_new.csv')
df1.head().T

                            0    1   2    3    4
Unnamed: 0                  0    1   2    3    4
race                        2    0   2    2    2
gender                      0    0   1    1    1
age                       154  446   3  100  266
admission_type_id           0    0   0    0    1
discharge_disposition_id    0    0   0    0    0
admission_source_id         6    6   6    6    1
time_in_hospital            2    1   1    0    2
num_lab_procedures         58   10  43   50   30
num_procedures              0    5   1    0    6
num_medications            17   12  15    7   15
diag_1                      8    1   0    0    0
diag_2                      0    0  21    0   20
diag_3                     19    0  20    0    0
number_diagnoses            6    3   4    2    6
max_glu_serum               2    2   2    2    2
A1Cresult                   2    2   2    2    2
metformin                   1    1   1    1    1
repaglinide                 1    1   1    1    1
nateglinide                 1    1   1    1    1
chlorpropamide              1    1   1    1    1
glimepiride                 1    1   1    1    1
acetohexamide               0    0   0    0    0
glipizide                   1    2   1    2    1
glyburide                   1    1   1    1    1
tolbutamide                 0    0   0    0    0
pioglitazone                1    1   1    1    1
rosiglitazone               1    1   1    1    1
acarbose                    1    1   1    1    1
miglitol                    1    1   1    1    1
troglitazone                0    0   0    0    0
tolazamide                  0    0   0    0    0
insulin                     3    1   3    2    2
glyburide-metformin         1    1   1    1    1
glipizide-metformin         0    0   0    0    0
glimepiride-pioglitazone    0    0   0    0    0
metformin-pioglitazone      0    0   0    0    0
change                      0    1   0    0    1
diabetesMed                 1    1   1    1    1
readmitted                  0    0   0    0    0

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98052 entries, 0 to 98051
Data columns (total 40 columns):
Unnamed: 0                  98052 non-null int64
race                        98052 non-null int64
gender                      98052 non-null int64
age                         98052 non-null int64
admission_type_id           98052 non-null int64
discharge_disposition_id    98052 non-null int64
admission_source_id         98052 non-null int64
time_in_hospital            98052 non-null int64
num_lab_procedures          98052 non-null int64
num_procedures              98052 non-null int64
num_medications             98052 non-null int64
diag_1                      98052 non-null int64
diag_2                      98052 non-null int64
diag_3                      98052 non-null int64
number_diagnoses            98052 non-null int64
max_glu_serum               98052 non-null int64
A1Cresult                   98052 non-null int64
metformin                   98052 non-null int64
repaglinide                 98052 non-null int64
nateglinide                 98052 non-null int64
chlorpropamide              98052 non-null int64
glimepiride                 98052 non-null int64
acetohexamide               98052 non-null int64
glipizide                   98052 non-null int64
glyburide                   98052 non-null int64
tolbutamide                 98052 non-null int64
pioglitazone                98052 non-null int64
rosiglitazone               98052 non-null int64
acarbose                    98052 non-null int64
miglitol                    98052 non-null int64
troglitazone                98052 non-null int64
tolazamide                  98052 non-null int64
insulin                     98052 non-null int64
glyburide-metformin         98052 non-null int64
glipizide-metformin         98052 non-null int64
glimepiride-pioglitazone    98052 non-null int64
metformin-pioglitazone      98052 non-null int64
change                      98052 non-null int64
diabetesMed                 98052 non-null int64
readmitted                  98052 non-null int64
dtypes: int64(40)
memory usage: 29.9 MB

In [4]:
df1.drop(['Unnamed: 0'],axis = 1,inplace=True)

In [5]:
x=df1.iloc[:,0:38].values
y=df1.iloc[:,38].values

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [7]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(x_train,y_train)
y_pred=logr.predict(x_test)
import sklearn.metrics as metrics
fpr,tpr,threshold=metrics.roc_curve(y_test,y_pred)
roc_auc_LR=metrics.auc(fpr,tpr)
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

0.8895517821630717

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,p=2)
knn.fit(x_train,y_train)
y_pred_knn=knn.predict(x_test)
fpr,tpr,threshold=metrics.roc_curve(y_test,y_pred)
roc_auc_knn=metrics.auc(fpr,tpr)
accuracy_score(y_test,y_pred_knn)

0.8786395390342155

In [9]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy',splitter='best')
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
fpr,tpr,threshold=metrics.roc_curve(y_test,y_pred)
roc_auc_dt=metrics.auc(fpr,tpr)
accuracy_score(y_pred,y_test)

0.7949110193258885

In [10]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=10,criterion='entropy')
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
fpr,tpr,threshold=metrics.roc_curve(y_test,y_pred)
roc_auc_rf=metrics.auc(fpr,tpr)
accuracy_score(y_pred,y_test)

0.8882769874050278

In [11]:
import pickle

In [12]:
pickle.dump(logr,open('logistic.pkl','wb'))
pickle.dump(knn,open('knn.pkl','wb'))
pickle.dump(rf,open('rf.pkl','wb'))